const path = '/icons'

export default {
	AIRPLANE_ICON: `${path}/airplane-icon.png`,
	AIRPORT_TRANSPORT_ICON: `${path}/airport-transport-icon.png`,
	AKUN_ICON: `${path}/akun-icon.png`,
	BACK_ICON: `${path}/back-icon.png`,
	BACK_WHITE_ICON: `${path}/back-white-icon.png`,
	CALENDAR_ICON: `${path}/calendar-icon.png`,
	EVENT_ICON: `${path}/event-icon.png`,
	HOME_ICON: `${path}/home-icon.png`,
	HOTEL_ICON: `${path}/hotel-icon.png`,
	KERETA_ICON: `${path}/kereta-icon.png`,
	NEXT_WHITE_ICON: `${path}/next-white-icon.png`,
	ORDER_ICON: `${path}/order-icon.png`,
	PESAWAT_ICON: `${path}/pesawat-icon.png`,
	PREV_WHITE_ICON: `${path}/prev-white-icon.png`,
	REWARD_ICON: `${path}/reward-icon.png`,
	ROUNDED_CLOSE_ICON: `${path}/rounded-close-icon.png`,
	SEARCH_ICON: `${path}/search-icon.png`,
	SEAT_ICON: `${path}/seat-icon.png`,
	SEWA_MOBIL_ICON: `${path}/sewa-mobil-icon.png`,
	SWAP_ICON: `${path}/swap-icon.png`,
	USER_ICON: `${path}/user-icon.png`,
	TODO_ICON: `${path}/todo-icon.png`,
}
